### ISSUE TITLE
It is not dismissing dialog when button clicked

### ISSUE THREAD

**Issue by androidlover5842** [kngfrhzs/panter-dialog#8]
it's not hiding when i set on click listener
here is my code 

                  ` new PanterDialog(getContext())
                            .setTitle("Flash "+StringFlashRB)
                            .setHeaderBackground(R.color.colorPrimaryDark)
                            .setMessage("Are you sure you want to Flash this "+StringFlashRB+" ?"+"\n"+path)
                            .setPositive("Flash", new View.OnClickListener() {
                                @Override
                                public void onClick(View view) {
                                    /*use sdcard/flash until this feature is ready*/
                                    Shell.SU.run("dd if="+path+" of="+mBootPath);

                                }
                            })
                            .setNegative("Cancel")
                            .withAnimation(Animation.POP)
                            .show;`

**Comment by ayaremin** [comment]
Yes you are right, I checked and it is not hiding, **I will fix this issue**, but for now you can hide it by using it like this

```
PanterDialog dialog = new PanterDialog(getContext());
dialog.setHeaderBackground(R.color.colorPrimaryDark)
                        .setMessage("Are you sure you want to Flash this "+StringFlashRB+" ?"+"\n"+path)
                        .setPositive("Flash", new View.OnClickListener() {
                            @Override
                            public void onClick(View view) {
                                /*use sdcard/flash until this feature is ready*/
                                dialog.dismiss();
                                Shell.SU.run("dd if="+path+" of="+mBootPath);

                            }
                        })
                        .setNegative("Cancel")
                        .withAnimation(Animation.POP)
                        .show();
```

**Comment by androidlover5842** [comment]
ok thanks a lot.

nedd to add `dialog.dismiss();` after `Shell.SU.run...` else it won't hide
